CREATE DATABASE db_matriculas
    DEFAULT CHARACTER SET = 'utf8mb4';

SHOW DATABASES;
USE db_matriculas;

SHOW TABLES;

-- SENTENCIAS DDL
-- CREAR UNA TABLA

CREATE TABLE alumno(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nro_documento VARCHAR(20) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(100)
);

DESCRIBE alumno;